### PR TITLE
Feature/lxl2292 cleanup sweb

### PR DESCRIPTION
**Pull request by jannistsiroyannis**

### CODE REVIEW

**Comment by olovy** [comment]
Too late to the party but I think the script should be placed in 2019/09, not 2019/10?

**Comment by jannistsiroyannis** [comment]
But I thought Bodil said we moved to a 6 week release cycle and the next release is in October!
But perhaps this shouldnt be run when releasing.

**Comment by niklasl** [comment]
Right, good point. AFAIR, the year/month-dir have been creation dates, not running dates (as some are run when ready, some at release depending on the ready state of some mapping issue). And that's just namespacing to avoid to many/long job names.

So no worries with the `10` in practice.

**Comment by niklasl** [comment]
(BTW, we regularly delete branches when merged to keep the branch list "tidy".)

**Pull request merged**
