### PR TITLE
Feature/lxl 2483 extended place descriptions 2

### PR DESCRIPTION
**Pull request by kwahlin**
Adds closeMatch relations to DDC, LCSH and FAST.
Adds exactMatch relations to Freebase, Geonames, TORA and YSO.
Something else that should be included?

### CODE REVIEW

**Review by olovy — APPROVED** [review]
:ship:

**Review by klngwll — APPROVED** [review]
LGTM!
One addition on top of my mind would be closeMatch(?) in getty: https://www.wikidata.org/wiki/Property:P1667

**Comment by olovy** [comment]
> LGTM! One addition on top of my mind would be closeMatch(?) in getty: https://www.wikidata.org/wiki/Property:P1667

exactMatch?

**Comment by kwahlin** [comment]
Sure, I'll add Getty IDs too. Think closeMatch should be the preferred relation as the resources there are subjects/concepts.

**Pull request merged**
