### PR TITLE
Add an extra (secret) x-withSilentUpdates option to OAI-PMH ListRecor…

### PR DESCRIPTION
**Pull request by jannistsiroyannis**
…ds/ListIdentifiers calls, to also select any records that where _silently_ changed within the interval.

### CODE REVIEW

**Comment by jannistsiroyannis** [comment]
Wait! There's a logic error here, don't reivew yet.

A modified outside the interval on one end, and a generation date outside on the other end will incorrectly be classified as "inside" the interval.

**Comment by jannistsiroyannis** [comment]
Now it should work ok!

**Review by andersju — APPROVED** [review]
LGTM!

**Review by olovy — APPROVED** [review]
LGTM

**Pull request merged**
