### PR TITLE
Search: Add 'exists-' filter prefix

### PR DESCRIPTION
**Pull request by olovy**
Make it possible to search for documents having a specific field or not.

### CODE REVIEW

**Review by lrosenstrom — APPROVED** [review]
Nice! Maybe substitute the query parameter 'exists' for 'has' so that the query would read better?  However, 'exists' might fit better in our ubiquitous language... :thinking:

**Review by klngwll — APPROVED** [review]
LGTM as far as I can see, nice with examples.

**Comment by klngwll** [comment]
> Nice! Maybe substitute the query parameter 'exists' for 'has' so that the query would read better? However, 'exists' might fit better in our ubiquitous language... 🤔

Isn't 'exists' the elastic name for the querytype? that makes me want to keep it, to make any referencing easier later on even though 'has' might be easier to read/write in the actual query.

**Review by andersju — APPROVED** [review]
LGTM! "exists" is indeed what it's called in ES ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html)) so +1 on sticking to that.

**Comment by lrosenstrom** [comment]
In that case I agree! :ship: :star:

**Comment by olovy** [comment]
Well, IMO, ES is just an "implementation detail" in this context so we should pick the prefix that makes the best API. 
But which is it? :thinking:

**Comment by andersju** [comment]
> Well, IMO, ES is just an "implementation detail" in this context so we should pick the prefix that makes the best API.
> But which one is it? thinking

From that perspective I think I do prefer `has-<field>`, and it pairs better with the existing `matches-<field>`. Or maybe `has-field-<field>` as a more future-proof solution, in case there could be things other than fields (perhaps more abstract things) that a record "has" that we'll want to be able to filter on?

**Review by niklasl — APPROVED** [review]
LGTM!

The XL API is (loosely) based on [The Linked Data API](https://github.com/UKGovLD/linked-data-api/blob/wiki/API_Query_Parameters.md) by the uk.gov, which uses `exists-` for this (with the same design). It is (likely) inspired by [EXISTS in SPARQL](https://www.w3.org/TR/sparql11-query/#func-filter-exists), which the LD-API was designed to be a GET-based query front for.

So while the equivalence in ES is incidental, and it is most certainly an implementation detail, I am very much in support of the `exists-` prefix, for these reasons.

Also, while `has` can read better, it becomes less obviously so with all the `has*`-named properties in KBV (`hasPart`, `hasVariant`, `hasReproduction` and some 24 more).

**Comment by olovy** [comment]
Thank you all for the input.

**Pull request merged**
