### PR TITLE
Feature/missing indicators

### PR DESCRIPTION
**Pull request by klngwll**
There are alot of missing indicators. I would prefer to merge and make new feature branches for chunks of those. Not entirely happy with how these turn out but I guess not loosing them is no.1 priority.

### CODE REVIEW

**Comment by niklasl** [comment]
I'd like to add them all tomorrow, if we can make a joint sweep then? Let's keep this branch until then to see if we can batch them all in.

**Comment by niklasl** [comment]
I think this is good to go now...

I would prefer to make the i1:s of bib 520 and 521 into "plan B" as well though (i.e. prefix both property and tokenMap values with `marc:`). We can't really use `typeNote` for those, as these values would have to remain strings if so (as opposed to using "micro-enum" lists (dropdowns) which is our plan for "required" plan B terms).

**Comment by niklasl** [comment]
I went ahead and made those final adjustments. @klngwll would you like to chime in, or should we call this done?

**Comment by klngwll** [comment]
Looks good!

**Pull request merged**
