### PR TITLE
Feature/summary to instance

### PR DESCRIPTION
**Pull request by kwahlin**
This script moves summaries not containing language down to instance for _all_ Text works.

### CODE REVIEW

**Review by olovy — APPROVED** [review]
LGTM!

**Comment by niklasl** [comment]
Has the marcframe logic been adapted to this requirement?

**Comment by klngwll** [comment]
> Has the marcframe logic been adapted to this requirement?

Yes default for conversion was made Instance a year back or so, but with a fallback entity for works. We have just lagged in the actual moving of them.

**Comment by niklasl** [comment]
> > Has the marcframe logic been adapted to this requirement?
> 
> Yes default for conversion was made Instance a year back or so, but with a fallback entity for works. We have just lagged in the actual moving of them.

Ah,  great; then all is in sync! (I faintly recalled "something amiss"; which is what this PR addresses!)

**Comment by klngwll** [comment]
Did we decide to move all other summaries than the bad shapes. I thought we were only moving if they also were from certain import channels? My memory need a refresh here :)

**Comment by kwahlin** [comment]
> Did we decide to move all other summaries than the bad shapes. I thought we were only moving if they also were from certain import channels? My memory need a refresh here :)

Yes, we discussed this in a format team meeting (22/6) and decided to move all the summaries. But we can discuss it again in the next meeting to fully establish the decision before we go through with any changes.

**Pull request merged**
