### PR TITLE
400 instead of 500 when POSTing new doc with temporary @id missing

### PR DESCRIPTION
**Pull request by andersju**
Before:

```
curl --request POST \
   --url http://localhost:8180/ \
   --header 'Authorization: Bearer <TOKEN>' \
   --header 'Content-Type: application/ld+json' \
   --header 'XL-Active-Sigel: Utb1' \
   --data '{"@graph":[{"@iddddd":"https://id.kb.se/TEMPID","@type":"Record","mainEntity":{"@id":"https://id.kb.se/TEMPID#it"},"descriptionConventions":[{"@type":"DescriptionConventions","code":"rda"}],"descriptionLanguage":{"@id":"https://id.kb.se/language/swe"}},{"@id":"https://id.kb.se/TEMPID#it","@type":"Person","familyName":"Testing","givenName":"Just"}]}'

{"status_code":500,"status":"Server Error","message":null,"stackTrace":["java.lang.NullPointerException" ... etc...
```

After:
```
{"status_code":400,"status":"Bad Request","message":"Document is missing temporary @id in Record"}
```

### CODE REVIEW

**Review by lrosenstrom — APPROVED** [review]
Nice! :ship:

**Comment by olovy** [comment]
:+1: Should we check for mainEntity `@id` + link also? or is that already handled elsewhere?

```
{
  "@graph": [
    {
      "@id": "https://id.kb.se/TEMPID",
      "mainEntity": {
        "@id": "https://id.kb.se/TEMPID#it"
      },
      ...
    },
    {
      "@id": "https://id.kb.se/TEMPID#it",
      ...
    }
  ]
}
```

**Comment by andersju** [comment]
> 
> Should we check for mainEntity `@id` + link also? or is that already handled elsewhere?
> 

Ah. Missing `@graph[0].mainEntity` `@id` causes 500 (NPE) when POSTing. Missing `@graph[1].@id` is accepted, but then causes 500 (NPE) when accessing the document. Should the latter be accepted or not (i.e. should it be possible to create documents that only have administrative metadata)? @olovy

**Comment by olovy** [comment]
> > Should we check for mainEntity `@id` + link also? or is that already handled elsewhere?
> 
> Ah. Missing `@graph[0].mainEntity` `@id` causes 500 (NPE) when POSTing. Missing `@graph[1].@id` is accepted, but then causes 500 (NPE) when accessing the document. Should the latter be accepted or not (i.e. should it be possible to create documents that only have administrative metadata)? @olovy

No. Record + Thing is the only valid form.

**Comment by andersju** [comment]
Now checking for id, mainEntity id and thing id + updated specs. @olovy @lrosenstrom

**Review by olovy — APPROVED** [review]
LGTM

Maybe check that 
`newDoc.getThingIdentifiers().first() == newDoc.data['@graph'][1]['@id']`
and
`newDoc.getId() != newDoc.getThingIdentifiers().first()`
?

**Review by olovy — APPROVED** [review]

**Pull request merged**
