### PR TITLE
Feature/lxl 4042 update more shelfmark sequences

### PR DESCRIPTION
**Pull request by lrosenstrom**
Include shelfmarkSequences with year based sequence codes in `qualifier` instead of `label` in the yearly bump. 

Tested locally on copies of https://libris.kb.se/katalogisering/1hcqjgvwzfpfjcxh and https://libris.kb.se/katalogisering/0fklzxfzxgvfcj23.

### CODE REVIEW

**Review by kwahlin — APPROVED** [review]
LGTM!

**Review by olovy — COMMENTED** [review]
If the ShelfMarkSequence contains YY or YYYY in both label and qualifier, two new ShelfMarkSequences will be created?

**Comment by lrosenstrom** [comment]
> If the ShelfMarkSequence contains YY or YYYY in both label and qualifier, two new ShelfMarkSequences will be created?

Good point. I updated the script.

**Review by olovy — APPROVED** [review]
:ship:

**Pull request merged**
