### PR TITLE
Add README for whelktool

### PR DESCRIPTION
**Pull request by olovy**
Quick initial draft.

### CODE REVIEW

**Review by andersju — APPROVED** [review]
Great start! Maybe add syntax highlighting to the code examples. I think GH markdown supports ```groovy.

**Comment by olovy** [comment]
> Great start! Maybe add syntax highlighting to the code examples. I think GH markdown supports ```groovy.

Good idea!

**Review by kwahlin — APPROVED** [review]
Good job!

**Review by lrosenstrom — APPROVED** [review]
Nice :tulip:

**Pull request merged**
