### PR TITLE
Search: Faster assembly of result by reducing number of DB calls

### PR DESCRIPTION
**Pull request by olovy**
When searching, for each request, hundreds of chips are loaded for e.g facets. This batches the DB requests and loads cards instead of full docs. ~40% faster when running locally on my machine.

### CODE REVIEW

**Review by jannistsiroyannis — APPROVED** [review]
I'm tired so proably not thinking straight.
I get that loading cards would be faster than full docs, but why would batching make a difference here (it's still the same number of queries right)? Is the idea to bypass the connectionPool (i thought that was supposed to be super cheap)?
Still, 40% is 40% :ship:

**Comment by olovy** [comment]
> I'm tired so proably not thinking straight.
> I get that loading cards would be faster than full docs, but why would batching make a difference here (it's still the same number of queries right)? Is the idea to bypass the connectionPool (i thought that was supposed to be super cheap)?
> Still, 40% is 40% ship

No it's (best case) two queries instead of 700 =)

**Review by lrosenstrom — APPROVED** [review]
Nice :ship:

**Review by andersju — APPROVED** [review]
:racing_car: :ship:

**Pull request merged**
