### PR TITLE
Feature/merge import rules

### PR DESCRIPTION
**Pull request by jannistsiroyannis**
This adds a commandline option to the batch-import which enables selective merging of incoming (bibliograhpic) records with existing ones.
This is done using a (json) rule-file and the computed history of existing records.

### CODE REVIEW

**Review by olovy — COMMENTED** [review]
So if I understand this correctly the following configuration would allow any properties to be added to existing docs?

```
{
    "rules": [
	{
            "operation": "add_if_none",
            "path": ["@graph", 1]
        }
    ]
}
```

**Review by olovy — APPROVED** [review]
:ship:

**Comment by jannistsiroyannis** [comment]
> So if I understand this correctly the following configuration would allow any properties to be added to existing docs?
> 
> ```
> {
>     "rules": [
> 	{
>             "operation": "add_if_none",
>             "path": ["@graph", 1]
>         }
>     ]
> }
> ```

Under @graph,1 yes, but not under @graph,0 (unless I've made a mistake).
But it's less .. invasive than it sounds, because you can never do deeper than the first list (except for the @graph one).

**Comment by olovy** [comment]
> > So if I understand this correctly the following configuration would allow any properties to be added to existing docs?
> > ```
> > {
> >     "rules": [
> > 	{
> >             "operation": "add_if_none",
> >             "path": ["@graph", 1]
> >         }
> >     ]
> > }
> > ```
> 
> Under @graph,1 yes, but not under @graph,0 (unless I've made a mistake). But it's less .. invasive than it sounds, because you can never do deeper than the first list (except for the @graph one).

I was thinking that it is a good thing. So that it is possible to let all properties be added without having to list them explicitly.

**Comment by olovy** [comment]
:ship:

**Pull request merged**
